config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users

  resources :hadith_collections
  resources :hadith_books
  resources :hadith_chapters

  resources :narrations
  resources :narrators

  get '/reset/:id' => 'narrations#reset_narration'
  post '/bulker' => 'narrations#bulker'
  post '/remove_narrator' => 'narrations#remove_narrator'

  get '/hadith_chapters/:hadith_book_id/new' => 'hadith_chapters#new'

  get '/hadith_books/:hadith_collection_id/new' => 'hadith_books#new'

  get '/test/bukhari/:link' => 'pages#test_bukhari'

  get '/test/bukhari/narrator/:search' => 'pages#test_bukhari_narrators'

  get '/test/muslim/:link' => 'pages#test_bukhari'

  post '/add_harmony' => 'resources#add_harmony'
  get '/get_harmonies/:id' => 'resources#get_harmonies'

  get '/assign_roles' => 'pages#assign_roles'

  get '/assign_roles/:id/:role' => 'pages#assign_roles'

  root 'pages#home'

end

app/models/narrator.rb
class Narrator < ActiveRecord::Base
end

app/controllers/narrators_controller.rb
class NarratorsController < ApplicationController
  before_action :set_narrator, only: [:show, :edit, :update, :destroy]

  # GET /narrators
  # GET /narrators.json
  def index
    @narrators = Narrator.all
  end

  # GET /narrators/1
  # GET /narrators/1.json
  def show
  end

  # GET /narrators/new
  def new
    @narrator = Narrator.new
  end

  # GET /narrators/1/edit
  def edit
  end

  # POST /narrators
  # POST /narrators.json
  def create
    @narrator = Narrator.new(narrator_params)

    respond_to do |format|
      if @narrator.save
        format.html { redirect_to @narrator, notice: 'Narrator was successfully created.' }
        format.json { render :show, status: :created, location: @narrator }
      else
        format.html { render :new }
        format.json { render json: @narrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /narrators/1
  # PATCH/PUT /narrators/1.json
  def update
    respond_to do |format|
      if @narrator.update(narrator_params)
        format.html { redirect_to @narrator, notice: 'Narrator was successfully updated.' }
        format.json { render :show, status: :ok, location: @narrator }
      else
        format.html { render :edit }
        format.json { render json: @narrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /narrators/1
  # DELETE /narrators/1.json
  def destroy
    @narrator.destroy
    respond_to do |format|
      format.html { redirect_to narrators_url, notice: 'Narrator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_narrator
      @narrator = Narrator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def narrator_params
      params.fetch(:narrator).permit!
    end
end

app/helpers/narrators_helper.rb
module NarratorsHelper
end

app/views/narrators/_form.html.erb
<%= form_for(@narrator) do |f| %>
  <% if @narrator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@narrator.errors.count, "error") %> prohibited this narrator from being saved:</h2>

      <ul>
      <% @narrator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :full_name %><br>
    <%= f.text_field :full_name, :class => "form-control" %>
  </div>


  <br>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/narrators/edit.html.erb
<h1>Editing Narrator</h1>

<%= render 'form' %>

<%= link_to 'Show', @narrator %> |
<%= link_to 'Back', narrators_path %>

app/views/narrators/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Narrators</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @narrators.each do |narrator| %>
      <tr>
        <td><%= link_to 'Show', narrator %></td>
        <td><%= link_to 'Edit', edit_narrator_path(narrator) %></td>
        <td><%= link_to 'Destroy', narrator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Narrator', new_narrator_path %>

app/views/narrators/new.html.erb
<h1>New Narrator</h1>

<%= render 'form' %>

<%= link_to 'Back', narrators_path %>

app/views/narrators/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_narrator_path(@narrator) %> |
<%= link_to 'Back', narrators_path %>