config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users

  resources :hadith_collections
  resources :hadith_books
  resources :hadith_chapters

  resources :narrations
  resources :narrators

  get '/reset/:id' => 'narrations#reset_narration'
  post '/bulker' => 'narrations#bulker'
  post '/remove_narrator' => 'narrations#remove_narrator'

  get '/hadith_chapters/:hadith_book_id/new' => 'hadith_chapters#new'

  get '/hadith_books/:hadith_collection_id/new' => 'hadith_books#new'

  get '/test/bukhari/:link' => 'pages#test_bukhari'

  get '/test/bukhari/narrator/:search' => 'pages#test_bukhari_narrators'

  get '/test/muslim/:link' => 'pages#test_bukhari'

  post '/add_harmony' => 'resources#add_harmony'
  get '/get_harmonies/:id' => 'resources#get_harmonies'

  get '/assign_roles' => 'pages#assign_roles'

  get '/assign_roles/:id/:role' => 'pages#assign_roles'

  root 'pages#home'

end

app/models/narration.rb
class Narration < ActiveRecord::Base

	belongs_to :hadith_chapter
	has_many :resources, as: :resourceable

	def reset_narration
		self.update(annotated_arabic: nil)
	end

	def self.bulk_add_narrator(name)

		prefixes = [
			"حَدَّثَنَا ", 
			"حَدَّثَنَا ", 
			"حَدَّثَنِي ",
			"حَدَّثَنِي",  
			"قَالَ أَخْبَرَنِي ", 
			"فَأَخْبَرَنِي ", 
			"َأَخْبَرَنِي ", 
			"أَخْبَرَنَا ", 
			"قَالَ ", 
			"قَالَتْ ",
			"سَأَلَ ",
			"عَنِ ", 
			"عَنْ ", 
			"أَنَّ ", 
			"سَمِعْتُ ", 
			"سَمِعَ "
		]

		n = HadithCollection.first.narrations

		ahadith = n.where("arabic like ?", "%#{name}%")

		filtered_name = name
		prefixes.each do |p|
			filtered_name = filtered_name.gsub(p, "")
		end

		ahadith.each do |h|

			original = h.arabic

			if h.annotated_arabic.present?
				annot = h.annotated_arabic

				if annot.include? '<span class="narrator id-this">'+filtered_name+'</span>'
				else
					new_version = annot.gsub!(filtered_name, '<span class="narrator id-this">'+filtered_name+'</span>')
					h.update(annotated_arabic: new_version)
				end
			else
				h.update(annotated_arabic: original)
				annot = h.annotated_arabic
				new_version = annot.gsub!(filtered_name, '<span class="narrator id-this">'+filtered_name+'</span>')
				h.update(annotated_arabic: new_version)
			end

		end

	end

	def self.remove_narrator(id, name)
		# <span class=\"narrator id-this\">عَبْدُ اللَّهِ بْنُ يُوسُفَ</span>
		hadith = Narration.find(id)
		sweep = hadith.annotated_arabic.gsub("<span class=\"narrator id-this\">#{name}</span>", "#{name}")
		hadith.update(annotated_arabic: sweep)
		# return sweep
	end

end

app/controllers/narrations_controller.rb
class NarrationsController < ApplicationController
  before_action :set_narration, only: [:show, :edit, :update, :destroy]

  # GET /narrations
  # GET /narrations.json
  def index
    @narrations = Narration.all
  end

  # GET /narrations/1
  # GET /narrations/1.json
  def show
  end

  # GET /narrations/new
  def new
    @narration = Narration.new
  end

  # GET /narrations/1/edit
  def edit
  end

  def reset_narration
    n = Narration.find(params[:id])
    n.reset_narration
  end

  def bulker
    Narration.bulk_add_narrator(params[:name])
    head :ok, content_type: "text/html"
  end

  def remove_narrator
    id = params[:id].to_i
    name = params[:name]
    Narration.remove_narrator(id, name)
    head :ok, content_type: "text/html"
  end

  # POST /narrations
  # POST /narrations.json
  def create
    @narration = Narration.new(narration_params)

    respond_to do |format|
      if @narration.save
        format.html { redirect_to @narration, notice: 'Narration was successfully created.' }
        format.json { render :show, status: :created, location: @narration }
      else
        format.html { render :new }
        format.json { render json: @narration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /narrations/1
  # PATCH/PUT /narrations/1.json
  def update
    respond_to do |format|
      if @narration.update(narration_params)
        format.html { redirect_to @narration, notice: 'Narration was successfully updated.' }
        format.json { render :show, status: :ok, location: @narration }
      else
        format.html { render :edit }
        format.json { render json: @narration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /narrations/1
  # DELETE /narrations/1.json
  def destroy
    @narration.destroy
    respond_to do |format|
      format.html { redirect_to narrations_url, notice: 'Narration was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_narration
      @narration = Narration.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def narration_params
      params.require(:narration).permit!
    end
end

app/helpers/narrations_helper.rb
module NarrationsHelper
end

app/views/narrations/_form.html.erb
<%= form_for(@narration) do |f| %>
  <% if @narration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@narration.errors.count, "error") %> prohibited this narration from being saved:</h2>

      <ul>
      <% @narration.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/narrations/edit.html.erb
<h1>Editing Narration</h1>

<%= render 'form' %>

<%= link_to 'Show', @narration %> |
<%= link_to 'Back', narrations_path %>

app/views/narrations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Narrations</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @narrations.each do |narration| %>
      <tr>
        <td><%= link_to 'Show', narration %></td>
        <td><%= link_to 'Edit', edit_narration_path(narration) %></td>
        <td><%= link_to 'Destroy', narration, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Narration', new_narration_path %>

app/views/narrations/new.html.erb
<h1>New Narration</h1>

<%= render 'form' %>

<%= link_to 'Back', narrations_path %>

app/views/narrations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_narration_path(@narration) %> |
<%= link_to 'Back', narrations_path %>