config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users

  resources :hadith_collections
  resources :hadith_books
  resources :hadith_chapters

  resources :narrations
  resources :narrators

  get '/reset/:id' => 'narrations#reset_narration'
  post '/bulker' => 'narrations#bulker'
  post '/remove_narrator' => 'narrations#remove_narrator'

  get '/hadith_chapters/:hadith_book_id/new' => 'hadith_chapters#new'

  get '/hadith_books/:hadith_collection_id/new' => 'hadith_books#new'

  get '/test/bukhari/:link' => 'pages#test_bukhari'

  get '/test/bukhari/narrator/:search' => 'pages#test_bukhari_narrators'

  get '/test/muslim/:link' => 'pages#test_bukhari'

  post '/add_harmony' => 'resources#add_harmony'
  get '/get_harmonies/:id' => 'resources#get_harmonies'

  get '/assign_roles' => 'pages#assign_roles'

  get '/assign_roles/:id/:role' => 'pages#assign_roles'

  root 'pages#home'

end

app/models/hadith_chapter.rb
class HadithChapter < ActiveRecord::Base

	belongs_to :hadith_book
	has_many :narrations, dependent: :destroy

	# after_create :set_position

	accepts_nested_attributes_for :narrations,
    allow_destroy: true

	# def set_position
	# 	chapters_list = self.hadith_book.hadith_chapters
	# 	if chapters_list.count > 1
	# 		self.update_attributes(position: chapters_list.count)
	# 	else
	# 		self.update_attributes(position: 1)
	# 	end
	# end

end

app/controllers/hadith_chapters_controller.rb
class HadithChaptersController < ApplicationController
  before_action :set_hadith_chapter, only: [:show, :edit, :update, :destroy]

  # GET /hadith_chapters
  # GET /hadith_chapters.json
  def index
    @hadith_chapters = HadithChapter.all
  end

  # GET /hadith_chapters/1
  # GET /hadith_chapters/1.json
  def show
  end

  # GET /hadith_chapters/new
  def new
    @hadith_chapter = HadithChapter.new
  end

  # GET /hadith_chapters/1/edit
  def edit
  end

  # POST /hadith_chapters
  # POST /hadith_chapters.json
  def create
    @hadith_chapter = HadithChapter.new(hadith_chapter_params)

    respond_to do |format|
      if @hadith_chapter.save
        format.html { redirect_to @hadith_chapter, notice: 'Hadith chapter was successfully created.' }
        format.json { render :show, status: :created, location: @hadith_chapter }
      else
        format.html { render :new }
        format.json { render json: @hadith_chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hadith_chapters/1
  # PATCH/PUT /hadith_chapters/1.json
  def update
    respond_to do |format|
      if @hadith_chapter.update(hadith_chapter_params)
        format.html { redirect_to @hadith_chapter, notice: 'Hadith chapter was successfully updated.' }
        format.json { render :show, status: :ok, location: @hadith_chapter }
      else
        format.html { render :edit }
        format.json { render json: @hadith_chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hadith_chapters/1
  # DELETE /hadith_chapters/1.json
  def destroy
    @hadith_chapter.destroy
    respond_to do |format|
      format.html { redirect_to hadith_chapters_url, notice: 'Hadith chapter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hadith_chapter
      @hadith_chapter = HadithChapter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hadith_chapter_params
      params.require(:hadith_chapter).permit!
    end
end

app/helpers/hadith_chapters_helper.rb
module HadithChaptersHelper
end

app/views/hadith_chapters/_form.html.erb
<%= form_for(@hadith_chapter) do |f| %>
  <% if @hadith_chapter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hadith_chapter.errors.count, "error") %> prohibited this hadith_chapter from being saved:</h2>

      <ul>
      <% @hadith_chapter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, :class => "form-control" %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes, :class => "form-control" %>
  </div>

  <%= f.hidden_field :hadith_book, value: params[:hadith_book_id] %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hadith_chapters/edit.html.erb
<h1>Editing Hadith Chapter</h1>

<%= render 'form' %>

<%= link_to 'Show', @hadith_chapter %> |
<%= link_to 'Back', hadith_chapters_path %>

app/views/hadith_chapters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Hadith Chapters</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hadith_chapters.each do |hadith_chapter| %>
      <tr>
        <td><%= link_to 'Show', hadith_chapter %></td>
        <td><%= link_to 'Edit', edit_hadith_chapter_path(hadith_chapter) %></td>
        <td><%= link_to 'Destroy', hadith_chapter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hadith chapter', new_hadith_chapter_path %>

app/views/hadith_chapters/new.html.erb
<h1>New Hadith Chapter</h1>

<%= render 'form' %>

<%= link_to 'Back', hadith_chapters_path %>

app/views/hadith_chapters/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_hadith_chapter_path(@hadith_chapter) %> |
<%= link_to 'Back', hadith_chapters_path %>